# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -X github.com/0xzer0x/go-pray/internal/version.version={{ .Version }}
      - -X github.com/0xzer0x/go-pray/internal/version.buildCommit={{ .FullCommit }}
      - -X github.com/0xzer0x/go-pray/internal/version.buildTime={{ .CommitDate }}

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
  - maintainer: Youssef Fathy <youssefessamasu@gmail.com>
    description: Prayer times CLI to remind you to Go pray
    formats:
      - deb
      - rpm

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs?:"
      - "^tests?:"
      - "^chore:"
      - '^v\d+\.\d+\.\d+'
      - Merge pull request
      - Merge branch

# NOTE: must be run in github actions (requires OID token)
binary_signs:
  - signature: ${artifact}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}.sig
    cmd: cosign
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}

aurs:
  - name: go-pray
    description: Prayer times CLI to remind you to Go pray
    homepage: https://github.com/0xzer0x/go-pray
    maintainers:
      - Youssef Fathy <youssefessamasu@gmail.com>
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/go-pray-bin.git
    commit_msg_template: "release: update to {{ .Tag }}"
    license: GPL-3.0-or-later
    depends:
      - alsa-lib
    package: |-
      # bin
      install -Dm755 ./go-pray "${pkgdir}/usr/bin/go-pray"

      # create temporary config file
      printf 'calculation: { method: "UAQ" }\nlocation: { lat: 0, long: 0 }\n' > tmpconfig.yml

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d"
      ./go-pray --config tmpconfig.yml completion bash > "${pkgdir}/usr/share/bash-completion/completions/go-pray"
      ./go-pray --config tmpconfig.yml completion zsh > "${pkgdir}/usr/share/zsh/site-functions/_go-pray"
      ./go-pray --config tmpconfig.yml completion fish > "${pkgdir}/usr/share/fish/vendor_completions.d/go-pray.fish"
