# INFO: Prayer times calculation method.
# https://aladhan.com/calculation-methods.
# Possible values:
# - EGYPT (Egyptian General Authority of Survey)
# - MWL (Muslim World League)
# - KARACHI (University of Islamic Sciences, Karachi)
# - UAQ (Umm al-Qura University, Makkah)
# - DUBAI (The Gulf Region)
# - ISNA (Islamic Society of North America)
# - KUWAIT (Kuwait)
# - QATAR (Qatar)
# - SINGAPORE (Singapore)
# - UOIF (Union Organization islamic de France)
method: EGYPT

# INFO: IANA time zone identifier.
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List.
timezone: Africa/Cairo

# INFO: Adhan mp3 to play at prayer time (daemon mode).
# Using environmental variables is supported.
adhan: $HOME/.local/share/qatami_takbeer.mp3

# INFO: location coordinates for prayer times calculation.
# https://www.mapcoordinates.net/en.
location:
  lat: 30.001780
  long: 31.290419
