version: 3
vars:
  INSTALL_DIR: $HOME/.local/bin
  RELEASE_VERSION:
    sh: git tag --sort=-version:refname | head -n 1
  RELEASE_COMMIT:
    sh: git rev-parse --verify {{ .RELEASE_VERSION }}
tasks:
  clean:
    cmd: go clean
  build:
    cmd: >-
      go build
      -ldflags="-X 'github.com/0xzer0x/go-pray/internal/version.version={{ .RELEASE_VERSION }}'
      -X 'github.com/0xzer0x/go-pray/internal/version.buildCommit={{ .RELEASE_COMMIT }}'
      -X 'github.com/0xzer0x/go-pray/internal/version.buildTime=$(date '+%F %T')'"
  install:
    deps:
      - build
    cmd: mv {{ .TASKFILE_DIR }}/go-pray {{ .INSTALL_DIR }}/go-pray
