name: Release
on:
  push:
    tags:
      - v*.*.*
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Check release commit
        run: |
          echo "::group::Checking tag commit matches latest commit on main"
          MAIN_SHA="$(git rev-parse --verify main)"
          if [ "${MAIN_SHA}" != "${GITHUB_SHA}" ]; then
            echo "::error title=Commit mismatch::Latest commit on main ($MAIN_SHA) does not match tag commit ($GITHUB_SHA)"
            exit 1
          fi
          echo "::endgroup::"

  release:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install dependencies
        run: sudo apt install libasound2-dev

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.7.0

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --clean
